### PR TITLE
Add ability to override association names for 63 char max workaround

### PR DESCRIPTION
**Pull request by brianjlowry**
PostgresSql has a maximum association name limit of 63 chars which can be an issue with foreign keys on larger table names. I've simply added an override method to change how the association name is handled. This gives the developer the ability to ensure there are no collisions from truncated association names. The alternative would be to download the source for PostgreSql, compile, keep up with all the patches, and continue to deploy...

### CODE REVIEW

**Comment by brianjlowry** [comment]
New to modifying another project... let me know if I did that right.

**Comment by roji** [comment]
@brianjlowry EF Core itself (not the Npgsql provider) already has a facility for truncating long identifiers to a database-specific maximum length. The provider (Npgsql in this case) [defines the maximum](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/blob/5488caf054f3b56c2b8ab33b34221d6aeffa8619/src/EFCore.PG/Metadata/Conventions/NpgsqlConventionSetBuilder.cs#L49) (63), and EF Core will truncate, [creating unique names](https://github.com/aspnet/EntityFrameworkCore/blob/d8b7ebbfabff3d2e8560c24b1ff14d1f4244ca6a/src/EFCore.Relational/Metadata/Conventions/Internal/SharedTableConvention.cs#L296) (by appending `~1`, `~2`...). So this doesn't seem necessary.

Also, in general we try not to solve general EF Core issues in Npgsql. If the existing solution (truncate to 63 with `~1`) isn't satisfactory in any way, it's preferable to solve it in EF Core itself as the same thing occurs in other databases.

One note though: as it is possible to compile your own version of PostgreSQL to raise the 63 limit, we can add an Npgsql option extension to allow the user to override the 63 default. This would allow you to recompile for, say, 128-long identifiers, and inform the Npgsql provider to instruct EF Core to truncate accordingly. However, I'd rather first wait for some to actually complain about this before implementing or opening an issue :)

Hope the above was clear. I'm going to close this for now, but please post back if you have any other questions or think something should still be done.

**Comment by brianjlowry** [comment]
Hi Roji,

I am not using .NET Core, but rather .NET Standard (4.7.2), and EntityFramework6 does not truncate properly - thus the reason I fixed it. I had to move away from core because of its lack of support for TPT, and then I ran into this issue. It seems like a transparent way to handle the problem as most developers would not have to deal with it unless they were looking for a solution like I was, and even though you've said no one is complaining about it, you can see plenty of people doing just that on StackOverflow. I found no real answers other then recompiling Postgres, but that seems ridiculous as you'd have to do it for all DB updates, security patches / hot fixes, etc.

My solution is a small code change that allows developers just the ability to override how the associations are named. Even if .NET Core handles it correctly, I'm not sure how this would greatly impact the code base.

**Comment by brianjlowry** [comment]
I want to add that this is a specific package dedicated to Npgsql, so I see even less concern about the changes, since it is specific to Postgres. Would you be ok with me re-submitting this pull request properly with these minor changes - look at what I changed... I just kicked the association naming to an override-able method.

**Comment by roji** [comment]
Ah apologies, I mistakenly read this whole PR as belonging to EF Core and not EF6... Please disregard what I wrote above - it's indeed irrelevant for EF6.

However, I'm not sure I understand how this would work... In order to override your extension point one would have to extend NpgsqlMigrationSqlGenerator. And this would imply changing NpgsqlServices as well, which basically amounts to creating a new version of the entire provider... Or am I missing something? If that's indeed the case, I'm not sure what good the extension point is...

Put another way, if this PR added actual uniquifying truncation similar to what EF Core does - truncating to 63 and using `~1` suffixes to maintain uniqueness - this would make much more sense to me, as it would provide support for long identifiers out of the box, without a need for forking the code. The PR in its current form seems to go halfway - it adds an extension point without actually solving the problem, forcing the problem to be solved again and again in forks...

One last comment... If you're going to do this kind of thing, it should probably be done for all identifier types: the current PR seems to work on primary keys, indices, foreign keys and tables, but neglects things such as column names, sequences, etc...

**Comment by brianjlowry** [comment]
Thanks - I created the extension point by decorating my DbContext with a DbConfigurationType attribute passing in the type of the custom DbConfiguration. The custom DbConfiguration has one line of code in its constructor: this.SetMigrationSqlGenerator("Npgsql", () => new LinkFuseMigrationPostgreSqlGenerator());

The LinkFuseMigrationPostgreSqlGenerator class inherits from NpgsqlMigrationSqlGenerator where I can override that method.

The only reason I did the solution this way was so that my code didn't leak into this library. I didn't realize that Core had an existing solution. I still think it's worthwhile to make the naming method virtual as I prefer to truncate each of the association column names, etc to a few chars so that I can read what it is instead of the same long names with ~1, ~2.

Let me know if I can clarify and if you are onboard with leaving virtual for the method call. If you're good with that, I will look into the column names and sequences, and re-do this PR.

**Comment by roji** [comment]
I think that a specific truncation/unifiquification logic does belong in the provider, rather than just an extension point that would have to be reimplemented every time. The 63 limitation is something affecting all EF6 users using PostgreSQL. So I'd rather see the problem solved - in the same way that EF Core solves it. Of course there's no reason not to allow users to change/customize it (by making the appropriate method virtual).

But looking at the PR again, there's something I don't understand... You apply the truncation strategy in the migrations SQL generator - but table names also need to get generated elsewhere, i.e. when querying and inserting into tables... How is that working for you? The PR as-is seems to allow truncation only when *creating* the table (via migrations), but not when *accessing* it.

Or are you only trying to solve the problem of long foreign keys, which only need to be created? If so that seems a bit partial for me, as the same problem exists for table and column names...

**Comment by brianjlowry** [comment]
I agree with you re: being in the provider, I just wasn't aware of a prior solution for Core and didn't want to force mine on other developers. I only applied the truncation strategy with the associations (not tables and columns) only because I never ran into that issue (and tackling that is a bit more work).

I'll take a look at it and re-submit a new PR.

**Comment by roji** [comment]
Thanks for understanding.

**Comment by McDoit** [comment]
Hello, a bit late to the party, but was this ever fixed/addressed?

**Comment by brianjlowry** [comment]
I never updated the PR because the changes have worked fine for me compiled locally, and I was likely side-tracked. I haven't re-visited this issue until your comment. @roji - was this ever addressed?

**Comment by McDoit** [comment]
I ended up creating a new migration sql generator, which takes the hash for the whole generated FK and replaces the last 10 chars with a git-like string representation of that hash

Dunno if i missed any case with it, but seems to be working

    class FkNameNpgsqlMigrationSqlGenerator : NpgsqlMigrationSqlGenerator
    {
        protected override void Convert(AddForeignKeyOperation addForeignKeyOperation)
        {
            addForeignKeyOperation.Name = Trunc(addForeignKeyOperation.Name);

            base.Convert(addForeignKeyOperation);
        }

        protected override void Convert(DropForeignKeyOperation dropForeignKeyOperation)
        {
            dropForeignKeyOperation.Name = Trunc(dropForeignKeyOperation.Name);

            base.Convert(dropForeignKeyOperation);
        }

        protected override void Convert(CreateIndexOperation createIndexOperation)
        {
            createIndexOperation.Name = Trunc(createIndexOperation.Name);

            base.Convert(createIndexOperation);
        }

        protected override void Convert(DropIndexOperation dropIndexOperation)
        {
            dropIndexOperation.Name = Trunc(dropIndexOperation.Name);

            base.Convert(dropIndexOperation);
        }

        private string Trunc(string name)
        {
            name = name.Replace('.', '_');

            if (name.Length > 63)
            {
                var hash = Hash(name);
                var newName = name.Remove(63 - hash.Length - 1);

                var nameHash = $"{newName}_{hash}";

                return nameHash;
            }

            return name;
        }

        private static string GenerateHashString(HashAlgorithm algo, string text)
        {
            // Compute hash from text parameter
            algo.ComputeHash(Encoding.UTF8.GetBytes(text));

            // Get has value in array of bytes
            var result = algo.Hash;

            // Return as hexadecimal string
            return string.Join(
                string.Empty,
                result.Select(x => x.ToString("x2")).Take(5));
        }

        public static string Hash(string text)
        {
            var result = default(string);

            using (var algo = new SHA1CryptoServiceProvider())
            {
                result = GenerateHashString(algo, text);
            }

            return result;
        }
    }

**Pull request closed without merging**
